[book]
title = "Bunpō Notes"
authors = ["Boyin Chen"]
language = "zh-cn"
multilingual = false
src = "src"

[build]
create-missing = true

[output.html.search]
enable = true

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js"]
